#!/usr/bin/env sh
# The MIT License
#
# Copyright (c) 2017 Gregory L. Dietsche <greg@gregd.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

if [ -z ${SMARTOS+x}  ]; then
	echo "The SMARTOS vaiable must be set and point to your SmartOS host."
	echo "For example if your SmartOS host is at 192.168.1.10 you should run this:"
	echo "export SMARTOS=192.168.1.10";
	exit 10
fi

vmadm="ssh $SMARTOS vmadm"
zlogin="ssh $SMARTOS -t zlogin"

if [ $# -eq 0 ]; then
        $vmadm list
        exit 0
fi

VM=$($vmadm list | grep $1 | cut -c1-38)
COUNT=$($vmadm list | grep $1 | wc -l)

if [ $COUNT -eq 0 ]; then
        echo No virtual machine matches $1.
        exit 20
fi
if [ $COUNT -gt 1 ]; then
        echo More than one virtual machine matches $1. Here are your choices:
        $vmadm list | grep $1
        exit 30
fi
$zlogin $VM
exit 0
